name: Build and Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '5.0.x'

      - name: Install OpenSSL 1.x
        run: |
          sudo apt-get update
          sudo apt-get install -y openssl=1.1.* libssl-dev=1.1.*

      - name: Restore dependencies
        run: dotnet restore --locked-mode

      - name: .Net Build Restore
        run: dotnet build

      - name: .Net Unit Test
        run: dotnet test
